Add responsive base
interglobalvision/pichon-mx pull request #37
Opened 2016-11-25 19:32 UTC by varffs

- migrates to flex grid
- add basic responsive translation to layout

2016-12-12 20:37 UTC, mikeyrayvon commented on archive-friend.php
>              <a href="<?php the_permalink() ?>"><?php the_post_thumbnail('col10-5to4'); ?></a>
its worth specifying which grid size the column count on image sizes refers to, and updating it for the grid item class name struction (ie `item-s-10-5to4` instead of `col10-5to4`)

2016-12-12 20:39 UTC, mikeyrayvon requested changes
update image sizes for grid item class name structure and add which grid size (s/m/l) each image width corresponds to

2016-12-13 18:37 UTC, varffs commented on archive-friend.php
>              <a href="<?php the_permalink() ?>"><?php the_post_thumbnail('col10-5to4'); ?></a>
As they all refer to `l` is this really worth doing? I was just about to do it but I don't feel like there is much point. Yes we need a convention for the future but in this project we can assume `l` (as I always would) and then if needed specify `s` or `m`

2016-12-16 17:19 UTC, mikeyrayvon commented on archive-friend.php
>              <a href="<?php the_permalink() ?>"><?php the_post_thumbnail('col10-5to4'); ?></a>
kay but i'll at least note that in a comment on the image sizes file

2016-12-16 17:21 UTC, mikeyrayvon approved these changes

2016-12-16 17:21 UTC, merged